schema_version = "1.0.0"

id = "theme_reverter"
version = "1.2.0"
name = "Theme Reverter"
tagline = "Revert themes from 5.0+ to 4.5 LTS and older"
maintainer = "byebyeLAN"
type = "add-on"

website = "https://extensions.blender.org/add-ons/theme-reverter/"

tags = ["System"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2026 byebyeLAN"
]

[permissions]
files = "Read and write theme XML files on disk"